name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Backend
        run: cd backend && npm install
      - name: Install Frontend
        run: cd frontend && npm install
